### ISSUE TITLE
关于vuewebapp的eslint问题

### ISSUE THREAD

**Issue by bin-Blog** [vincentSea/vue-webapp#4]
我下载了你的vuewebapp后在我的IDE中打开出现如下问题：
file: 'file:///d%3A/My-GitHub/GitHubClone/VueJS/vueWebapp/src/routers.js'
severity: '错误'
message: 'Parsing error: The keyword 'export' is reserved'
at: '1,1'
source: 'eslint'
该如何解决此问题？

**Comment by scarecrowdu** [comment]
@bin-Blog 是不是编辑器的eslint提示语法导致的问题，之前项目没有用到eslint规则

**Comment by bin-Blog** [comment]
是的，vscode打开项目文件以后eslint校验报错




发自网易邮箱大师


在2017年07月13日 17:35，Mr.Du<notifications@github.com> 写道：

@bin-Blog 是不是编辑器的eslint提示语法导致的问题，之前项目没有用到eslint规则
