### ISSUE TITLE
banner轮播

### ISSUE THREAD

**Issue by devphc** [vincentSea/vue-webapp#8]
好像不轮播？

**Comment by devphc** [comment]
是在 develop 分支里

**Comment by vincentSea** [comment]
@devphc 请问你是拿是不是最先的分支代码，如果是的话，我这里首页和详情页的图片都能正常轮播。代码有没有提示报什么错呢

**Comment by scarecrowdu** [comment]
@devphc  请问你是拿是不是最新的分支代码，如果是的话，我这里首页和详情页的图片都能正常轮播。代码有没有提示报什么错呢
